# Generated by Django 4.2.3 on 2023-07-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='frame_rate',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='recording',
            name='frames_count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='frames_images_count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='keyboard_events_count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='mouse_events_count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='mouse_events_distance',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='start',
            field=models.PositiveBigIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='text_elements_count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='text_sentiment_score',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='text_sizes_count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MouseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recording')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recording')),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recording')),
            ],
        ),
    ]
