# Generated by Django 4.2.3 on 2023-07-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recording_frame_rate_recording_frames_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboardevent',
            name='stamp',
            field=models.PositiveBigIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mouseevent',
            name='stamp',
            field=models.PositiveBigIntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='frame_rate',
            field=models.IntegerField(default = 15),
        ),
        migrations.AlterField(
            model_name='recording',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
