# Generated by Django 4.2.3 on 2023-07-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_keyboardevent_stamp_mouseevent_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='frame_rate',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='recording',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
