# Generated by Django 4.2.3 on 2023-07-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_recording_frame_rate_alter_recording_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='start',
            new_name='rec_start',
        ),
    ]
