# Generated by Django 4.2.3 on 2023-07-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_start_recording_rec_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardevent',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard_events', to='app.recording'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='app.recording'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='width',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mouseevent',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_events', to='app.recording'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='app.account'),
        ),
    ]
