# Generated by Django 4.2.3 on 2023-07-14 14:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=10000)),
                ('logo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('rec_start', models.PositiveBigIntegerField()),
                ('frame_rate', models.IntegerField(default=15)),
                ('frames_count', models.IntegerField()),
                ('frames_images_count', models.IntegerField()),
                ('mouse_events_count', models.IntegerField()),
                ('keyboard_events_count', models.IntegerField()),
                ('mouse_events_distance', models.FloatField()),
                ('text_elements_count', models.IntegerField()),
                ('text_sizes_count', models.IntegerField()),
                ('text_sentiment_score', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='web.account')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidates', models.ManyToManyField(to='web.account')),
                ('recordings', models.ManyToManyField(to='web.recording')),
            ],
        ),
        migrations.CreateModel(
            name='MouseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.PositiveBigIntegerField()),
                ('button', models.CharField(max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_events', to='web.recording')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='web.recording')),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.PositiveBigIntegerField()),
                ('key', models.CharField(max_length=20)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard_events', to='web.recording')),
            ],
        ),
    ]
