# Generated by Django 4.2.3 on 2023-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='frame_rate',
            field=models.IntegerField(default=15, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='frames_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='frames_images_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='keyboard_events_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='mouse_events_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='mouse_events_distance',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='rec_start',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='text_elements_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='text_sentiment_score',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='text_sizes_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
