# Generated by Django 4.2.3 on 2023-07-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_account_company_alter_account_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
