# Generated by Django 4.2.3 on 2023-07-19 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='candidates',
        ),
        migrations.AddField(
            model_name='request',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='web.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='frame_rate',
            field=models.IntegerField(default=15),
        ),
    ]
