# Generated by Django 4.2.3 on 2023-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_request_candidates_request_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='recordings',
            field=models.ManyToManyField(related_name='requests', to='web.recording'),
        ),
    ]
