# Generated by Django 4.2.3 on 2023-08-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_request_recordings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web.account')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.recording')),
            ],
        ),
    ]
