# Generated by Django 4.2.3 on 2023-08-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_recording_favorite_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestfavorite',
            name='favorite_ptr',
        ),
        migrations.RemoveField(
            model_name='requestfavorite',
            name='request',
        ),
        migrations.DeleteModel(
            name='RecordingFavorite',
        ),
        migrations.DeleteModel(
            name='RequestFavorite',
        ),
        migrations.AddField(
            model_name='favorite',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web.recording'),
            preserve_default=False,
        ),
    ]
