# Generated by Django 4.2.3 on 2023-08-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_requestfavorite_favorite_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
