# Generated by Django 4.2.3 on 2023-08-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_delete_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web.recording')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.recording')),
            ],
        ),
    ]
