# Generated by Django 4.2.3 on 2023-08-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='recording',
        ),
        migrations.CreateModel(
            name='RequestFavorite',
            fields=[
                ('favorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.favorite')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web.request')),
            ],
            bases=('web.favorite',),
        ),
        migrations.CreateModel(
            name='RecordingFavorite',
            fields=[
                ('favorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.favorite')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web.recording')),
            ],
            bases=('web.favorite',),
        ),
    ]
